# Generated by Django 4.2 on 2024-12-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Farmer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                (
                    "email",
                    models.EmailField(default="unknown@example.com", max_length=254),
                ),
                ("location", models.CharField(max_length=255)),
                ("soil_type", models.CharField(blank=True, max_length=255, null=True)),
                ("password", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="GovernmentAgency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agency_name", models.CharField(max_length=255)),
                ("contact_person", models.CharField(default="Unknown", max_length=255)),
                (
                    "email",
                    models.EmailField(default="unknown@example.com", max_length=254),
                ),
                ("region", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="NGO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization_name",
                    models.CharField(default="Unknown Organization", max_length=255),
                ),
                ("contact_person", models.CharField(default="Unknown", max_length=255)),
                (
                    "email",
                    models.EmailField(default="unknown@example.com", max_length=254),
                ),
                ("focus_area", models.CharField(blank=True, max_length=255, null=True)),
                ("password", models.CharField(max_length=128)),
            ],
        ),
    ]
