# Generated by Django 4.2 on 2024-12-01 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recommendapp", "0002_farmer_governmentagency_ngo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ngo",
            name="contact_person",
        ),
    ]
